### ISSUE TITLE
Gamification 

### ISSUE THREAD

**Issue by Baldrani** [CatFishTeam/fromton#4]
- [X] Think user xp
- [X] edit user + faker + migration
- [X] define cap
- [x] create notification

**Comment by lesageanthony** [comment]
creation de compte + 1ere connexion = 1 xp
like un fromage = 2xp
add a friend = 3xp 
note un fromage = 5xp
add un fromage = 8xp
level 1: 1xp
level 2: 10 xp
level 3: 50 xp
level 4: 100 xp
level 5: 250 xp
level 6: 500 xp
level 7: 250 xp
level 8: 1000 xp 
après de 500 en 500
